config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  # titleは空なし
  validates :title, presence: true
  # bodyは空なし、最大２００文字
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :books, dependent: :destroy
    attachment:profile_image


    validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
    validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_current_user, {only: [:edit, :update]}
def ensure_current_user
  @book = Book.find(params[:id])
  if current_user.id != @book.user_id
    redirect_to books_path
  end
end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_current_user, {only: [:edit, :update]}
def ensure_current_user
  if current_user.id != params[:id].to_i
    redirect_to user_path(current_user)
  end
end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Option</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do%>
            <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: "jpg", fallback: "no_image.jpg", size: "50x50" %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td>
            <%= book.body %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/edit.html.erb
<main>
  <% if @book.errors.any? %>
    <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Books</h1>

        <%= form_with model: @book, local:true do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :option %>
            <%= f.text_area :body, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success mt-3" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        <span>|</span>
        <%= link_to "Back", books_path %>

      </div>
    </div>
  </div>
</main>

app/views/books/index.hml.erb
<main>

  <% if @book.errors.any? %>
    <P><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="container px-5 px-sm-0">
    <div class="row">

      <%= render "users/post", user: @user, book: @book %>
      <%= render "books/list",books: @books %>

    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>

  <% if @book.errors.any? %>
    <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="container px-5 px-sm-0">
    <div class="row">

      <%= render "users/post", user: @user, book: @book %>
      <%= render "books/list",books: @books %>

    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <%= flash[:notice] %>

  <div class="container">
    <div class="row">

      <%= render "users/post", user: @user, book: @new_book %>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>

        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: "jpg", fallback: "no_image.jpg", size: "40x40" %><br>
                <%= link_to user_path(@user.id) do %>
                  <%= @user.name %>
                <% end %>
              </td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <% if @book.user_id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
                <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-danger btn-sm", "data-confirm" => "本当に削除しますか？" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <!--px-3=>padding-right,left ,mx-auto中央寄せ-->
      <h1 class="px-3 mx-auto">
        Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<%= render 'layouts/flash' %>
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!
        </h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <!--ボタンの囲み部分の幅等指定-->
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <!--btn-info青色ボタン,btn-smボタンの大きさ,btn-block横幅いっぱいのブロックレベルボタン,mb-3下側のマージン1rem,-->
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <!--btn-success緑色ボタン,btn-smボタンの大きさ,btn-block横幅いっぱいのブロックレベルボタン,mb-3下側のマージン1rem,-->
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3 sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_flash.html.erb
<% if notice %>
  <p><%= notice %></p>
<% end %>
<% if alert %>
  <p><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

          <%= link_to root_path, class: "navbar-brand" do %>
            <span>Bookers</span>
          <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                    <i class="fas fa-home">Home</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users">Users</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fas fa-book-open">Books</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt">logout</i>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home">Home</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link">About</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus">sign up</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt">login</i>
                  <% end %>
                </li>
              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_post.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <td>name</td>
        <td><%= user.name %></td>
      </tr>
       <tr>
        <td>option</td>
        <td><%= user.introduction %></td>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" do %>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, url: books_path, local:true do |f| %>
    <div form-group>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div form-group>
      <%= f.label :option %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div form-group>
      <%= f.submit "Create Book", class: "btn btn-success mt-3" %>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<main>
  <% if @user.errors.any? %>
    <p><%= @user.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h2>User info</h2>

        <%= form_with model: @user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.attachment_field :profile_image, class: "form-control-file" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %>
            <%= f.text_area :introduction, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary mt-3" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <%= render "users/post", user: @user, book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>

        <table class="table table-hover">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: "jpg", fallback: "no_image.jpg", size: "50x50" %>
                </td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <%= render "layouts/flash" %>

  <div class="container px-5 px-sm-0">
    <div class="row">

      <%= render "users/post", user: @user, book: @book %>
      <%= render "books/list", books: @books %>

    </div>
   </div>

</main>